version: '3.8'
services:
  redis:
    build:
      context: .
      dockerfile: ./dockerfile/redis
    restart: always
    command: >
      redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf

  mysql:
    build:
      context: .
      dockerfile: ./dockerfile/mysql
    restart: always
    command: >
        --character-set-server=utf8mb4
        --collation-server=utf8mb4_unicode_ci
        --general_log=ON
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: general
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: UTC
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./init/mysql:/docker-entrypoint-initdb.d
  
  postgres:
    build:
      context: .
      dockerfile: ./dockerfile/postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: general
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/pgdata
      - ./init/postgres:/docker-entrypoint-initdb.d
    
  mariadb:
    build:
      context: .
      dockerfile: ./dockerfile/mariadb
    restart: always
    command: >
        --character-set-server=utf8mb4
        --collation-server=utf8mb4_unicode_ci
        --general_log=ON
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: general
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: UTC
    ports:
        - "3366:3306"
    volumes:
      - ./data/mariadb:/var/lib/mysql
      - ./init/mariadb:/docker-entrypoint-initdb.d